-- Independent of special_periods: meeting collections never affect service statistics.
create table public.service_meeting_collections (
  id integer generated by default as identity primary key,
  name_ko text not null check (length(btrim(name_ko)) between 1 and 160),
  name_zh text not null default '' check (length(name_zh) <= 160),
  start_date date not null,
  end_date date not null,
  home_visible_until date not null,
  home_position text not null default 'after_service' check (home_position in ('after_service', 'top')),
  collapse_suggestions boolean not null default true,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  archived_at timestamptz,
  check (start_date <= end_date and end_date <= home_visible_until)
);

create table public.service_meeting_notes (
  id integer generated by default as identity primary key,
  event_id integer unique references public.calendar_events(id) on delete set null,
  collection_id integer not null references public.service_meeting_collections(id) on delete restrict,
  title_ko text not null check (length(btrim(title_ko)) between 1 and 200),
  title_zh text not null default '' check (length(title_zh) <= 200),
  body_ko text not null check (length(btrim(body_ko)) between 1 and 30000),
  body_zh text not null default '' check (length(body_zh) <= 30000),
  excerpt_ko text not null,
  excerpt_zh text not null,
  reading_minutes_ko integer not null,
  reading_minutes_zh integer not null,
  event_date_snapshot date not null,
  event_time_snapshot text not null default '',
  event_place_snapshot text not null default '',
  event_leader_snapshot text not null default '',
  author_user_id integer references public.app_users(id) on delete set null,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  archived_at timestamptz
);
create index service_meeting_notes_collection_date on public.service_meeting_notes(collection_id, event_date_snapshot, event_time_snapshot);

alter table public.service_meeting_collections enable row level security;
alter table public.service_meeting_notes enable row level security;
revoke all on public.service_meeting_collections, public.service_meeting_notes from public, anon, authenticated;
grant select on public.service_meeting_collections, public.service_meeting_notes to anon, authenticated;
create policy meeting_collections_read on public.service_meeting_collections for select to anon, authenticated
  using ((select private.request_session_user_id()) is not null and (archived_at is null or (select private.request_is_admin())));
create policy meeting_notes_read on public.service_meeting_notes for select to anon, authenticated
  using ((select private.request_session_user_id()) is not null and (archived_at is null or (select private.request_is_admin())));

create function public.save_service_meeting_collection(p_token uuid, p_id integer, p_expected_updated_at timestamptz, p_data jsonb)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user integer; v_row public.service_meeting_collections; v_end date;
begin
  v_user := public.verify_session(p_token);
  if not exists(select 1 from public.app_users where id=v_user and role in ('admin','developer')) then
    raise exception '관리자만 모임 정리를 수정할 수 있습니다';
  end if;
  if p_id is not null then
    select * into v_row from public.service_meeting_collections where id=p_id for update;
    if not found then raise exception '모음을 찾을 수 없습니다'; end if;
    if v_row.updated_at is distinct from p_expected_updated_at then return jsonb_build_object('ok',false,'conflict',true); end if;
    if v_row.archived_at is not null then raise exception '보관된 모음입니다'; end if;
  end if;
  v_end := (p_data->>'end_date')::date;
  if p_id is null then
    insert into public.service_meeting_collections(name_ko,name_zh,start_date,end_date,home_visible_until,home_position,collapse_suggestions)
    values(btrim(p_data->>'name_ko'),coalesce(p_data->>'name_zh',''),(p_data->>'start_date')::date,v_end,
      coalesce((p_data->>'home_visible_until')::date,v_end+14),coalesce(p_data->>'home_position','after_service'),coalesce((p_data->>'collapse_suggestions')::boolean,true))
    returning * into v_row;
  else
    update public.service_meeting_collections set name_ko=btrim(p_data->>'name_ko'),name_zh=coalesce(p_data->>'name_zh',''),
      start_date=(p_data->>'start_date')::date,end_date=v_end,home_visible_until=coalesce((p_data->>'home_visible_until')::date,v_end+14),
      home_position=coalesce(p_data->>'home_position','after_service'),collapse_suggestions=coalesce((p_data->>'collapse_suggestions')::boolean,true),
      archived_at=case when coalesce((p_data->>'archive')::boolean,false) then clock_timestamp() else null end,
      updated_at=clock_timestamp() where id=p_id returning * into v_row;
  end if;
  return jsonb_build_object('ok',true,'id',v_row.id);
end $$;
revoke all on function public.save_service_meeting_collection(uuid,integer,timestamptz,jsonb) from public, anon, authenticated;
grant execute on function public.save_service_meeting_collection(uuid,integer,timestamptz,jsonb) to anon, authenticated;

create function public.save_service_meeting_note(p_token uuid, p_id integer, p_event_id integer, p_collection_id integer, p_expected_updated_at timestamptz, p_data jsonb)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user integer; v_row public.service_meeting_notes; v_event public.calendar_events; v_ko text; v_zh text;
begin
  v_user := public.verify_session(p_token);
  if not exists(select 1 from public.app_users where id=v_user and role in ('admin','developer')) then
    raise exception '관리자만 모임 정리를 수정할 수 있습니다';
  end if;
  -- Match calendar deletion's lock order (event, then note). Avoid stale snapshots/deadlocks.
  if p_id is not null then
    select event_id into p_event_id from public.service_meeting_notes where id=p_id;
  end if;
  if p_event_id is not null then
    select * into v_event from public.calendar_events where id=p_event_id for update;
    if not found and p_id is null then raise exception '일정을 찾을 수 없습니다'; end if;
  end if;
  if p_id is not null then
    select * into v_row from public.service_meeting_notes where id=p_id for update;
    if not found then raise exception '글을 찾을 수 없습니다'; end if;
    if v_row.updated_at is distinct from p_expected_updated_at then return jsonb_build_object('ok',false,'conflict',true); end if;
    if v_row.archived_at is not null then raise exception '보관된 글입니다'; end if;
  elsif p_event_id is null then
    raise exception '일정을 선택해 주세요';
  elsif exists(select 1 from public.service_meeting_notes where event_id=p_event_id) then
    return jsonb_build_object('ok',false,'conflict',true);
  end if;
  perform 1 from public.service_meeting_collections where id=p_collection_id and archived_at is null for share;
  if not found then raise exception '사용할 수 없는 모음입니다'; end if;
  v_ko := btrim(p_data->>'body_ko'); v_zh := btrim(coalesce(p_data->>'body_zh',''));
  if p_id is null then
    insert into public.service_meeting_notes(event_id,collection_id,title_ko,title_zh,body_ko,body_zh,excerpt_ko,excerpt_zh,
      reading_minutes_ko,reading_minutes_zh,event_date_snapshot,event_time_snapshot,event_place_snapshot,event_leader_snapshot,author_user_id)
    values(p_event_id,p_collection_id,btrim(p_data->>'title_ko'),coalesce(p_data->>'title_zh',''),v_ko,v_zh,
      left(regexp_replace(v_ko,'\s+',' ','g'),180),left(regexp_replace(v_zh,'\s+',' ','g'),180),
      greatest(1,ceil(length(v_ko)/300.0)::integer),greatest(1,ceil(length(v_zh)/300.0)::integer),
      v_event.event_date,v_event.time,coalesce(v_event.place,''),coalesce(v_event.leader_name,''),v_user) returning * into v_row;
  else
    update public.service_meeting_notes set collection_id=p_collection_id,title_ko=btrim(p_data->>'title_ko'),title_zh=coalesce(p_data->>'title_zh',''),
      body_ko=v_ko,body_zh=v_zh,excerpt_ko=left(regexp_replace(v_ko,'\s+',' ','g'),180),excerpt_zh=left(regexp_replace(v_zh,'\s+',' ','g'),180),
      reading_minutes_ko=greatest(1,ceil(length(v_ko)/300.0)::integer),reading_minutes_zh=greatest(1,ceil(length(v_zh)/300.0)::integer),
      archived_at=case when coalesce((p_data->>'archive')::boolean,false) then clock_timestamp() else null end,
      updated_at=clock_timestamp() where id=p_id returning * into v_row;
  end if;
  return jsonb_build_object('ok',true,'id',v_row.id);
end $$;
revoke all on function public.save_service_meeting_note(uuid,integer,integer,integer,timestamptz,jsonb) from public, anon, authenticated;
grant execute on function public.save_service_meeting_note(uuid,integer,integer,integer,timestamptz,jsonb) to anon, authenticated;

create function public.snapshot_service_meeting_event() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if TG_OP='DELETE' then
    update public.service_meeting_notes set event_date_snapshot=old.event_date,event_time_snapshot=coalesce(old.time,''),
      event_place_snapshot=coalesce(old.place,''),event_leader_snapshot=coalesce(old.leader_name,''),updated_at=clock_timestamp() where event_id=old.id;
    return old;
  end if;
  update public.service_meeting_notes set event_date_snapshot=new.event_date,event_time_snapshot=coalesce(new.time,''),
    event_place_snapshot=coalesce(new.place,''),event_leader_snapshot=coalesce(new.leader_name,''),updated_at=clock_timestamp() where event_id=new.id;
  return new;
end $$;
revoke all on function public.snapshot_service_meeting_event() from public, anon, authenticated;
create trigger snapshot_service_meeting_event_delete before delete on public.calendar_events
for each row execute function public.snapshot_service_meeting_event();
create trigger snapshot_service_meeting_event_update after update of event_date,time,place,leader_name on public.calendar_events
for each row when (old.event_date is distinct from new.event_date or old.time is distinct from new.time or old.place is distinct from new.place or old.leader_name is distinct from new.leader_name)
execute function public.snapshot_service_meeting_event();

-- Preserve the existing rename implementation and all its authorization/notification rules.
alter function public.rename_user_name_references(uuid,text,text) set schema private;
revoke all on function private.rename_user_name_references(uuid,text,text) from public, anon, authenticated;
create function public.rename_user_name_references(p_token uuid,p_old text,p_new text) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_result jsonb;
begin
  v_result := private.rename_user_name_references(p_token,p_old,p_new);
  if coalesce((v_result->>'ok')::boolean,false) then
    update public.service_meeting_notes set event_leader_snapshot=public.rename_in_name_list(event_leader_snapshot,p_old,p_new),updated_at=clock_timestamp()
    where p_old=any(select btrim(v) from unnest(string_to_array(event_leader_snapshot,',')) v);
  end if;
  return v_result;
end $$;
revoke all on function public.rename_user_name_references(uuid,text,text) from public, anon, authenticated;
grant execute on function public.rename_user_name_references(uuid,text,text) to anon, authenticated;
