-- 세대 추가를 다른 열린 앱에 즉시 반영한다.
-- 기존 place_change_signals에 created를 섞으면 구형 앱이 삭제로 오해하므로 별도 표를 쓴다.

create table if not exists public.unit_creation_signals (
  id bigint generated by default as identity primary key,
  building_id integer not null references public.buildings(id) on delete cascade,
  unit_id integer not null unique references public.units(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.unit_creation_signals enable row level security;
revoke all on public.unit_creation_signals from public, anon, authenticated;
grant select on public.unit_creation_signals to anon, authenticated;

drop policy if exists unit_creation_signals_select on public.unit_creation_signals;
create policy unit_creation_signals_select on public.unit_creation_signals
  for select to anon, authenticated using (true);

create or replace function private.signal_unit_creation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.unit_creation_signals (building_id, unit_id)
  values (new.building_id, new.id)
  on conflict (unit_id) do nothing;
  return new;
end;
$$;

revoke all on function private.signal_unit_creation() from public, anon, authenticated;

drop trigger if exists signal_unit_creation_after_insert on public.units;
create trigger signal_unit_creation_after_insert
after insert on public.units
for each row execute function private.signal_unit_creation();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'unit_creation_signals'
  ) then
    alter publication supabase_realtime add table public.unit_creation_signals;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgrelid = 'public.units'::regclass
      and tgname = 'signal_unit_creation_after_insert'
      and not tgisinternal
  ) then
    raise exception '세대 생성 신호 트리거가 없습니다';
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'unit_creation_signals'
  ) then
    raise exception 'unit_creation_signals가 Realtime publication에 없습니다';
  end if;
  if has_table_privilege('anon', 'public.unit_creation_signals', 'INSERT,UPDATE,DELETE,TRUNCATE') then
    raise exception 'anon이 세대 생성 신호를 쓸 수 있습니다';
  end if;
end $$;

notify pgrst, 'reload schema';
